# Generated by Django 2.2.1 on 2019-05-29 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('parser', models.CharField(choices=[('Parser1', 'Parser1'), ('Parser2', 'Parser2'), ('Parser3', 'Parser3'), ('Parser4', 'Parser4'), ('Parser5', 'Parser5')], max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File_Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.IntegerField(null=True)),
                ('email_date', models.DateTimeField(null=True)),
                ('parser', models.CharField(max_length=15, null=True)),
                ('options', models.CharField(choices=[('Options1', 'Options1'), ('Options2', 'Options2'), ('Options3', 'Options3'), ('Options4', 'Options4'), ('Options5', 'Options5')], max_length=15)),
                ('sended', models.BooleanField()),
                ('file', models.FileField(upload_to='')),
                ('createAdd', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.Customers')),
            ],
            options={
                'ordering': ['createAdd'],
            },
        ),
    ]
