# Generated by Django 2.2.1 on 2019-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_parser',
            name='emailID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_parser',
            name='email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_parser',
            name='parser',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
