# Generated by Django 2.2.1 on 2019-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20190529_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_parser',
            name='emailID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='file_parser',
            name='email_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='file_parser',
            name='parser',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
