# Generated by Django 2.2.1 on 2019-07-02 14:28

import Apps.Report.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_auto_20190529_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.IntegerField(null=True)),
                ('email_date', models.DateField(null=True)),
                ('parser', models.CharField(max_length=15, null=True)),
                ('options', models.CharField(choices=[('Options1', 'Options1'), ('Options2', 'Options2'), ('Options3', 'Options3'), ('Options4', 'Options4'), ('Options5', 'Options5')], max_length=15)),
                ('sent', models.BooleanField()),
                ('file', models.FileField(upload_to=Apps.Report.models.movie_directory_path)),
                ('createAdd', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report.Customers')),
            ],
            options={
                'ordering': ['createAdd'],
            },
        ),
        migrations.DeleteModel(
            name='File_Parser',
        ),
    ]
