# Generated by Django 2.2.1 on 2019-07-17 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20190702_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileparser',
            name='createAdd',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
